import { db, agentsTable, propertiesTable } from "@workspace/db";

const agents = [
  {
    name: "Karim Benali",
    email: "k.benali@immodz.dz",
    phone: "+213 555 12 34 56",
    photo: "https://picsum.photos/seed/agent1/200/200",
    agency: "Immo Excellence Alger",
    wilaya: "Alger",
    bio: "Spécialiste de l'immobilier haut de gamme à Alger depuis 12 ans. Expert en appartements et villas de prestige.",
    rating: 4.9,
    reviewCount: 87,
    listingCount: 34,
    yearsExperience: 12,
    languages: ["Français", "Arabe", "Anglais"],
    verified: true,
  },
  {
    name: "Amira Khelil",
    email: "a.khelil@immodz.dz",
    phone: "+213 661 23 45 67",
    photo: "https://picsum.photos/seed/agent2/200/200",
    agency: "Agence Oran Prestige",
    wilaya: "Oran",
    bio: "15 ans d'expérience dans l'immobilier à Oran. Spécialisée dans les biens résidentiels et commerciaux.",
    rating: 4.7,
    reviewCount: 63,
    listingCount: 28,
    yearsExperience: 15,
    languages: ["Français", "Arabe"],
    verified: true,
  },
  {
    name: "Youcef Mammeri",
    email: "y.mammeri@immodz.dz",
    phone: "+213 770 34 56 78",
    photo: "https://picsum.photos/seed/agent3/200/200",
    agency: "Constantine Immo",
    wilaya: "Constantine",
    bio: "Expert immobilier à Constantine. Connaissance approfondie du marché local et des meilleures opportunités d'investissement.",
    rating: 4.6,
    reviewCount: 41,
    listingCount: 19,
    yearsExperience: 8,
    languages: ["Français", "Arabe"],
    verified: true,
  },
  {
    name: "Naima Boudaoud",
    email: "n.boudaoud@immodz.dz",
    phone: "+213 550 45 67 89",
    photo: "https://picsum.photos/seed/agent4/200/200",
    agency: "Annaba Immobilier",
    wilaya: "Annaba",
    bio: "Agente immobilière passionnée à Annaba. Je vous accompagne dans chaque étape de votre projet immobilier.",
    rating: 4.5,
    reviewCount: 29,
    listingCount: 15,
    yearsExperience: 6,
    languages: ["Français", "Arabe"],
    verified: true,
  },
  {
    name: "Rachid Hadj",
    email: "r.hadj@immodz.dz",
    phone: "+213 698 56 78 90",
    photo: "https://picsum.photos/seed/agent5/200/200",
    agency: "Tizi Ouzou Habitat",
    wilaya: "Tizi Ouzou",
    bio: "Spécialiste de l'immobilier en Kabylie. Expert en terrains et constructions traditionnelles.",
    rating: 4.4,
    reviewCount: 22,
    listingCount: 12,
    yearsExperience: 5,
    languages: ["Français", "Arabe", "Tamazight"],
    verified: true,
  },
  {
    name: "Fatima Zerrouki",
    email: "f.zerrouki@immodz.dz",
    phone: "+213 773 67 89 01",
    photo: "https://picsum.photos/seed/agent6/200/200",
    agency: "Setif Premium Realty",
    wilaya: "Sétif",
    bio: "Agente immobilière expérimentée à Sétif. Experte en projets résidentiels et investissements locatifs.",
    rating: 4.8,
    reviewCount: 55,
    listingCount: 23,
    yearsExperience: 10,
    languages: ["Français", "Arabe"],
    verified: true,
  },
  {
    name: "Mohamed Touati",
    email: "m.touati@immodz.dz",
    phone: "+213 551 78 90 12",
    photo: "https://picsum.photos/seed/agent7/200/200",
    agency: "Blida Immo Group",
    wilaya: "Blida",
    bio: "Courtier immobilier dynamique à Blida. Réseau étendu et connaissance parfaite du marché régional.",
    rating: 4.3,
    reviewCount: 18,
    listingCount: 11,
    yearsExperience: 4,
    languages: ["Français", "Arabe"],
    verified: false,
  },
  {
    name: "Samia Belkacem",
    email: "s.belkacem@immodz.dz",
    phone: "+213 660 89 01 23",
    photo: "https://picsum.photos/seed/agent8/200/200",
    agency: "Batna Résidences",
    wilaya: "Batna",
    bio: "Experte immobilière à Batna avec une solide connaissance du marché régional. Disponible 7j/7.",
    rating: 4.6,
    reviewCount: 34,
    listingCount: 17,
    yearsExperience: 7,
    languages: ["Français", "Arabe"],
    verified: true,
  },
];

const propertiesSeed = [
  // ALGER - For Sale
  {
    title: "Appartement F4 luxueux à Hydra",
    titleAr: "شقة F4 فاخرة في حيدرة",
    description: "Magnifique appartement F4 de 130m² situé dans le quartier résidentiel prisé de Hydra. Entièrement rénové avec des finitions haut de gamme, double vitrage, parquet au sol. Vue panoramique sur la mer Méditerranée. Immeuble sécurisé avec gardien.",
    type: "sale",
    category: "apartment",
    price: 45000000,
    priceUnit: "DZD",
    area: 130,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    floor: 5,
    totalFloors: 8,
    wilaya: "Alger",
    commune: "Hydra",
    address: "Résidence El Yasmine, Hydra, Alger",
    latitude: 36.7417,
    longitude: 3.0261,
    images: [
      "https://picsum.photos/seed/prop1a/800/600",
      "https://picsum.photos/seed/prop1b/800/600",
      "https://picsum.photos/seed/prop1c/800/600",
      "https://picsum.photos/seed/prop1d/800/600",
    ],
    amenities: ["Parking", "Ascenseur", "Gardien", "Terrasse", "Climatisation", "Cuisine équipée", "Vue mer", "Interphone"],
    featured: true,
    available: true,
    yearBuilt: 2018,
    agentId: 1,
  },
  {
    title: "Villa moderne à Ben Aknoun",
    titleAr: "فيلا عصرية في بن عكنون",
    description: "Splendide villa individuelle R+2 de 350m² dans la zone résidentielle de Ben Aknoun. Grand jardin arborisé de 500m², piscine privée, 5 chambres avec dressing, salon marocain, cuisine américaine. Finitions luxueuses.",
    type: "sale",
    category: "villa",
    price: 120000000,
    priceUnit: "DZD",
    area: 350,
    rooms: 8,
    bedrooms: 5,
    bathrooms: 4,
    floor: 0,
    totalFloors: 3,
    wilaya: "Alger",
    commune: "Ben Aknoun",
    address: "Lotissement El Feth, Ben Aknoun, Alger",
    latitude: 36.7635,
    longitude: 3.0066,
    images: [
      "https://picsum.photos/seed/prop2a/800/600",
      "https://picsum.photos/seed/prop2b/800/600",
      "https://picsum.photos/seed/prop2c/800/600",
    ],
    amenities: ["Piscine", "Jardin", "Garage", "Gardien", "Domotique", "Salon marocain", "Climatisation", "Cuisine équipée", "Terrasse", "Barbecue"],
    featured: true,
    available: true,
    yearBuilt: 2020,
    agentId: 1,
  },
  {
    title: "Studio meublé à Bab Ezzouar",
    titleAr: "استوديو مفروش في باب الزوار",
    description: "Studio entièrement meublé de 38m² idéalement situé près de l'université de Bab Ezzouar. Parfait pour étudiant ou jeune actif. Cuisine équipée, salle de bain moderne.",
    type: "rent",
    category: "studio",
    price: 35000,
    priceUnit: "DZD",
    area: 38,
    rooms: 1,
    bedrooms: 0,
    bathrooms: 1,
    floor: 2,
    totalFloors: 5,
    wilaya: "Alger",
    commune: "Bab Ezzouar",
    address: "Cité universitaire, Bab Ezzouar, Alger",
    latitude: 36.7237,
    longitude: 3.1773,
    images: [
      "https://picsum.photos/seed/prop3a/800/600",
      "https://picsum.photos/seed/prop3b/800/600",
    ],
    amenities: ["Meublé", "WiFi", "Cuisine équipée", "Ascenseur"],
    featured: false,
    available: true,
    yearBuilt: 2015,
    agentId: 1,
  },
  {
    title: "F3 à louer à El Biar",
    titleAr: "F3 للإيجار في البيار",
    description: "Appartement F3 de 85m² dans le quartier calme d'El Biar. Bien entretenu, lumineux, avec balcon vue sur mer. Proche écoles et commerces.",
    type: "rent",
    category: "apartment",
    price: 65000,
    priceUnit: "DZD",
    area: 85,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    floor: 3,
    totalFloors: 6,
    wilaya: "Alger",
    commune: "El Biar",
    address: "Rue des Glycines, El Biar, Alger",
    latitude: 36.7700,
    longitude: 3.0331,
    images: [
      "https://picsum.photos/seed/prop4a/800/600",
      "https://picsum.photos/seed/prop4b/800/600",
      "https://picsum.photos/seed/prop4c/800/600",
    ],
    amenities: ["Balcon", "Vue mer", "Parking", "Interphone"],
    featured: false,
    available: true,
    yearBuilt: 2010,
    agentId: 1,
  },
  {
    title: "Local commercial avenue Didouche Mourad",
    titleAr: "محل تجاري بشارع ديدوش مراد",
    description: "Local commercial de 80m² en rez-de-chaussée sur l'une des artères commerciales les plus actives d'Alger. Vitrine de 6m, tout commerce autorisé, flux piétonnier important.",
    type: "commercial",
    category: "commercial",
    price: 150000,
    priceUnit: "DZD",
    area: 80,
    rooms: 1,
    bedrooms: 0,
    bathrooms: 1,
    floor: 0,
    totalFloors: 1,
    wilaya: "Alger",
    commune: "Alger Centre",
    address: "Avenue Didouche Mourad, Alger",
    latitude: 36.7430,
    longitude: 3.0580,
    images: [
      "https://picsum.photos/seed/prop5a/800/600",
      "https://picsum.photos/seed/prop5b/800/600",
    ],
    amenities: ["Vitrine", "Climatisation", "Toilettes", "Accès PMR"],
    featured: true,
    available: true,
    yearBuilt: 2005,
    agentId: 1,
  },

  // ORAN
  {
    title: "Appartement F5 à Bir El Djir",
    titleAr: "شقة F5 في بئر الجير",
    description: "Grand appartement F5 de 160m² dans la nouvelle ville de Bir El Djir. Résidence sécurisée, parking souterrain, proche du centre commercial Bab El Wahran.",
    type: "sale",
    category: "apartment",
    price: 32000000,
    priceUnit: "DZD",
    area: 160,
    rooms: 5,
    bedrooms: 4,
    bathrooms: 2,
    floor: 4,
    totalFloors: 10,
    wilaya: "Oran",
    commune: "Bir El Djir",
    address: "Résidence Mirabell, Bir El Djir, Oran",
    latitude: 35.6547,
    longitude: -0.6181,
    images: [
      "https://picsum.photos/seed/prop6a/800/600",
      "https://picsum.photos/seed/prop6b/800/600",
      "https://picsum.photos/seed/prop6c/800/600",
    ],
    amenities: ["Parking", "Ascenseur", "Gardien", "Interphone", "Balcon", "Climatisation"],
    featured: true,
    available: true,
    yearBuilt: 2019,
    agentId: 2,
  },
  {
    title: "Villa à Es Sénia",
    titleAr: "فيلا في السانية",
    description: "Belle villa de 280m² à Es Sénia avec jardin paysagé de 300m². Maison familiale avec 4 chambres, double salon, garage pour 2 voitures. Quartier résidentiel calme.",
    type: "sale",
    category: "villa",
    price: 75000000,
    priceUnit: "DZD",
    area: 280,
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    floor: 0,
    totalFloors: 2,
    wilaya: "Oran",
    commune: "Es Sénia",
    address: "Cité des orangers, Es Sénia, Oran",
    latitude: 35.6357,
    longitude: -0.6048,
    images: [
      "https://picsum.photos/seed/prop7a/800/600",
      "https://picsum.photos/seed/prop7b/800/600",
    ],
    amenities: ["Jardin", "Garage", "Climatisation", "Salon marocain", "Cuisine équipée"],
    featured: false,
    available: true,
    yearBuilt: 2016,
    agentId: 2,
  },
  {
    title: "F3 meublé à louer centre d'Oran",
    titleAr: "F3 مفروش للإيجار وسط وهران",
    description: "Appartement F3 de 90m² entièrement meublé au cœur d'Oran. Idéal pour expatriés ou professionnels. Toutes commodités à pied.",
    type: "rent",
    category: "apartment",
    price: 75000,
    priceUnit: "DZD",
    area: 90,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    floor: 2,
    totalFloors: 5,
    wilaya: "Oran",
    commune: "Oran Centre",
    address: "Rue Larbi Ben M'Hidi, Oran",
    latitude: 35.6977,
    longitude: -0.6329,
    images: [
      "https://picsum.photos/seed/prop8a/800/600",
      "https://picsum.photos/seed/prop8b/800/600",
    ],
    amenities: ["Meublé", "WiFi", "Climatisation", "Balcon"],
    featured: false,
    available: true,
    yearBuilt: 2012,
    agentId: 2,
  },
  {
    title: "Bureau commercial à Oran",
    titleAr: "مكتب تجاري في وهران",
    description: "Espace de bureaux de 120m² au 3ème étage d'un immeuble moderne à Oran. Open space aménageable, salle de réunion, parking. Idéal pour entreprise PME.",
    type: "commercial",
    category: "office",
    price: 120000,
    priceUnit: "DZD",
    area: 120,
    rooms: 4,
    bedrooms: 0,
    bathrooms: 2,
    floor: 3,
    totalFloors: 7,
    wilaya: "Oran",
    commune: "Oran Centre",
    address: "Immeuble Business Park, Oran",
    latitude: 35.7010,
    longitude: -0.6253,
    images: [
      "https://picsum.photos/seed/prop9a/800/600",
      "https://picsum.photos/seed/prop9b/800/600",
    ],
    amenities: ["Parking", "Ascenseur", "Climatisation", "Salle de réunion", "Fibre optique"],
    featured: false,
    available: true,
    yearBuilt: 2021,
    agentId: 2,
  },

  // CONSTANTINE
  {
    title: "Appartement vue Rhumel Constantine",
    titleAr: "شقة بإطلالة على الرمال - قسنطينة",
    description: "Rare appartement F4 de 115m² avec vue imprenable sur les gorges du Rhumel. Situation privilégiée, immeuble colonial rénové, parquet d'époque. Le charme de Constantine.",
    type: "sale",
    category: "apartment",
    price: 28000000,
    priceUnit: "DZD",
    area: 115,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    floor: 2,
    totalFloors: 4,
    wilaya: "Constantine",
    commune: "Constantine Ville",
    address: "Boulevard de l'Indépendance, Constantine",
    latitude: 36.3613,
    longitude: 6.6147,
    images: [
      "https://picsum.photos/seed/prop10a/800/600",
      "https://picsum.photos/seed/prop10b/800/600",
      "https://picsum.photos/seed/prop10c/800/600",
    ],
    amenities: ["Vue gorges", "Parquet", "Haute plafond", "Balcon"],
    featured: true,
    available: true,
    yearBuilt: 1950,
    agentId: 3,
  },
  {
    title: "F3 à Ali Mendjeli Constantine",
    titleAr: "F3 في علي منجلي - قسنطينة",
    description: "Appartement F3 neuf de 95m² dans la nouvelle ville d'Ali Mendjeli. Immeuble récent, ascenseur, parking. Quartier moderne avec toutes commodités.",
    type: "sale",
    category: "apartment",
    price: 18000000,
    priceUnit: "DZD",
    area: 95,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    floor: 3,
    totalFloors: 6,
    wilaya: "Constantine",
    commune: "Ali Mendjeli",
    address: "Résidence Es-Salam, Ali Mendjeli, Constantine",
    latitude: 36.2833,
    longitude: 6.5667,
    images: [
      "https://picsum.photos/seed/prop11a/800/600",
      "https://picsum.photos/seed/prop11b/800/600",
    ],
    amenities: ["Neuf", "Parking", "Ascenseur", "Terrasse"],
    featured: false,
    available: true,
    yearBuilt: 2022,
    agentId: 3,
  },
  {
    title: "Maison traditionnelle Casbah Constantine",
    titleAr: "منزل تقليدي في قصبة قسنطينة",
    description: "Authentique maison de la casbah de 200m² à réhabiliter. Architecture arabo-andalouse, patio central, 5 pièces réparties sur 2 niveaux. Patrimoine exceptionnel à valoriser.",
    type: "sale",
    category: "house",
    price: 12000000,
    priceUnit: "DZD",
    area: 200,
    rooms: 5,
    bedrooms: 4,
    bathrooms: 2,
    floor: 0,
    totalFloors: 2,
    wilaya: "Constantine",
    commune: "Vieux Constantine",
    address: "Casbah de Constantine",
    latitude: 36.3670,
    longitude: 6.6200,
    images: [
      "https://picsum.photos/seed/prop12a/800/600",
      "https://picsum.photos/seed/prop12b/800/600",
    ],
    amenities: ["Patio", "Architecture historique", "Terrasse toit"],
    featured: false,
    available: true,
    yearBuilt: 1880,
    agentId: 3,
  },

  // ANNABA
  {
    title: "F4 bord de mer Annaba",
    titleAr: "F4 على ساحل البحر - عنابة",
    description: "Exceptionnel appartement F4 de 120m² à quelques mètres de la plage de Annaba. Vue mer directe depuis les 2 balcons, résidence récente sécurisée.",
    type: "sale",
    category: "apartment",
    price: 38000000,
    priceUnit: "DZD",
    area: 120,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    floor: 6,
    totalFloors: 9,
    wilaya: "Annaba",
    commune: "Annaba Centre",
    address: "Corniche Annaba",
    latitude: 36.9006,
    longitude: 7.7673,
    images: [
      "https://picsum.photos/seed/prop13a/800/600",
      "https://picsum.photos/seed/prop13b/800/600",
      "https://picsum.photos/seed/prop13c/800/600",
    ],
    amenities: ["Vue mer", "Balcon", "Parking", "Gardien", "Ascenseur"],
    featured: true,
    available: true,
    yearBuilt: 2017,
    agentId: 4,
  },
  {
    title: "Villa à Seraïdi Annaba",
    titleAr: "فيلا في سرايدي - عنابة",
    description: "Charmante villa de montagne à Seraïdi, le Monaco d'Algérie. 220m² sur terrain de 800m², vue sur mer et forêt. Architecture coloniale, 4 chambres, jardin.",
    type: "sale",
    category: "villa",
    price: 55000000,
    priceUnit: "DZD",
    area: 220,
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    floor: 0,
    totalFloors: 2,
    wilaya: "Annaba",
    commune: "Seraïdi",
    address: "Route de Seraïdi, Annaba",
    latitude: 36.8897,
    longitude: 7.6500,
    images: [
      "https://picsum.photos/seed/prop14a/800/600",
      "https://picsum.photos/seed/prop14b/800/600",
    ],
    amenities: ["Vue mer", "Jardin", "Climatisation", "Terrasse", "Cheminée"],
    featured: false,
    available: true,
    yearBuilt: 1970,
    agentId: 4,
  },

  // TIZI OUZOU
  {
    title: "Terrain à bâtir Tizi Ouzou",
    titleAr: "أرض للبناء في تيزي وزو",
    description: "Terrain plat de 500m² viabilisé dans lotissement résidentiel de Tizi Ouzou. Eau, gaz, électricité. Permis de construire R+3 possible. Excellent investissement.",
    type: "sale",
    category: "land",
    price: 15000000,
    priceUnit: "DZD",
    area: 500,
    rooms: 0,
    bedrooms: 0,
    bathrooms: 0,
    wilaya: "Tizi Ouzou",
    commune: "Tizi Ouzou Ville",
    address: "Lotissement Ait Yahia, Tizi Ouzou",
    latitude: 36.7170,
    longitude: 4.0480,
    images: [
      "https://picsum.photos/seed/prop15a/800/600",
      "https://picsum.photos/seed/prop15b/800/600",
    ],
    amenities: ["Viabilisé", "Raccordé eau", "Raccordé gaz", "Raccordé électricité", "Titre foncier"],
    featured: false,
    available: true,
    yearBuilt: null,
    agentId: 5,
  },
  {
    title: "Maison kabyle Tizi Ouzou",
    titleAr: "بيت قبائلي في تيزي وزو",
    description: "Authentique maison kabyle de 180m² sur terrain de 300m² avec vue sur le Djurdjura. 4 pièces, jardin avec arbres fruitiers, terrasse panoramique.",
    type: "sale",
    category: "house",
    price: 22000000,
    priceUnit: "DZD",
    area: 180,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    floor: 0,
    totalFloors: 2,
    wilaya: "Tizi Ouzou",
    commune: "Ait Mahmoud",
    address: "Village Ait Mahmoud, Tizi Ouzou",
    latitude: 36.7200,
    longitude: 4.1000,
    images: [
      "https://picsum.photos/seed/prop16a/800/600",
      "https://picsum.photos/seed/prop16b/800/600",
    ],
    amenities: ["Vue montagne", "Jardin", "Terrasse", "Arbres fruitiers"],
    featured: false,
    available: true,
    yearBuilt: 1995,
    agentId: 5,
  },

  // SÉTIF
  {
    title: "F4 neuf à louer Sétif",
    titleAr: "F4 جديد للإيجار في سطيف",
    description: "Appartement F4 de 110m² dans résidence de standing à Sétif. Neuf, jamais habité, 3 chambres, double salon. À 5 min du centre-ville.",
    type: "rent",
    category: "apartment",
    price: 55000,
    priceUnit: "DZD",
    area: 110,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    floor: 2,
    totalFloors: 5,
    wilaya: "Sétif",
    commune: "Sétif Centre",
    address: "Résidence Florale, Sétif",
    latitude: 36.1810,
    longitude: 5.4058,
    images: [
      "https://picsum.photos/seed/prop17a/800/600",
      "https://picsum.photos/seed/prop17b/800/600",
    ],
    amenities: ["Neuf", "Parking", "Ascenseur", "Balcon", "Climatisation"],
    featured: false,
    available: true,
    yearBuilt: 2023,
    agentId: 6,
  },
  {
    title: "Local commercial Sétif Centre",
    titleAr: "محل تجاري في وسط سطيف",
    description: "Local commercial de 50m² bien situé dans la zone piétonne de Sétif. Fort passage journalier, activité commerciale intense. Idéal boutique, pharmacie, restauration.",
    type: "commercial",
    category: "commercial",
    price: 80000,
    priceUnit: "DZD",
    area: 50,
    rooms: 1,
    bedrooms: 0,
    bathrooms: 1,
    floor: 0,
    totalFloors: 1,
    wilaya: "Sétif",
    commune: "Sétif Centre",
    address: "Zone piétonne, Sétif",
    latitude: 36.1900,
    longitude: 5.4100,
    images: [
      "https://picsum.photos/seed/prop18a/800/600",
    ],
    amenities: ["Zone piétonne", "Vitrine", "Climatisation"],
    featured: false,
    available: true,
    yearBuilt: 2000,
    agentId: 6,
  },
  {
    title: "Villa F6 à Sétif",
    titleAr: "فيلا F6 في سطيف",
    description: "Grande villa familiale de 320m² sur terrain de 500m² dans quartier résidentiel de Sétif. 5 chambres, salon d'apparat, piscine, garage 2 voitures.",
    type: "sale",
    category: "villa",
    price: 85000000,
    priceUnit: "DZD",
    area: 320,
    rooms: 8,
    bedrooms: 5,
    bathrooms: 4,
    floor: 0,
    totalFloors: 3,
    wilaya: "Sétif",
    commune: "Ain El Kebira",
    address: "Cité El Badr, Sétif",
    latitude: 36.1600,
    longitude: 5.4500,
    images: [
      "https://picsum.photos/seed/prop19a/800/600",
      "https://picsum.photos/seed/prop19b/800/600",
      "https://picsum.photos/seed/prop19c/800/600",
    ],
    amenities: ["Piscine", "Jardin", "Garage", "Salon marocain", "Climatisation", "Cuisine équipée"],
    featured: true,
    available: true,
    yearBuilt: 2021,
    agentId: 6,
  },

  // BLIDA
  {
    title: "Appartement F3 à Blida",
    titleAr: "شقة F3 في البليدة",
    description: "Appartement F3 de 80m² dans résidence sécurisée à Blida, proche du marché central. 2 chambres, salon, cuisine équipée, balcon avec vue sur l'Atlas blidéen.",
    type: "sale",
    category: "apartment",
    price: 16000000,
    priceUnit: "DZD",
    area: 80,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    floor: 3,
    totalFloors: 5,
    wilaya: "Blida",
    commune: "Blida Centre",
    address: "Résidence les Orangers, Blida",
    latitude: 36.4722,
    longitude: 2.8278,
    images: [
      "https://picsum.photos/seed/prop20a/800/600",
      "https://picsum.photos/seed/prop20b/800/600",
    ],
    amenities: ["Balcon", "Vue montagne", "Parking", "Interphone"],
    featured: false,
    available: true,
    yearBuilt: 2014,
    agentId: 7,
  },

  // BATNA
  {
    title: "F4 à louer Batna",
    titleAr: "F4 للإيجار في باتنة",
    description: "Appartement F4 de 100m² bien entretenu au centre de Batna. Lumineux, bien orienté, 3 chambres, grand salon. Proche de toutes commodités.",
    type: "rent",
    category: "apartment",
    price: 45000,
    priceUnit: "DZD",
    area: 100,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    floor: 1,
    totalFloors: 4,
    wilaya: "Batna",
    commune: "Batna Centre",
    address: "Rue de la Liberté, Batna",
    latitude: 35.5547,
    longitude: 6.1740,
    images: [
      "https://picsum.photos/seed/prop21a/800/600",
      "https://picsum.photos/seed/prop21b/800/600",
    ],
    amenities: ["Balcon", "Climatisation", "Parking"],
    featured: false,
    available: true,
    yearBuilt: 2008,
    agentId: 8,
  },
  {
    title: "Terrain agricole Batna",
    titleAr: "أرض زراعية في باتنة",
    description: "Grand terrain agricole de 2000m² à Batna, irrigation disponible, titre foncier propre. Idéal pour agriculture maraîchère ou projet agro-touristique.",
    type: "sale",
    category: "land",
    price: 8000000,
    priceUnit: "DZD",
    area: 2000,
    rooms: 0,
    bedrooms: 0,
    bathrooms: 0,
    wilaya: "Batna",
    commune: "Ain Touta",
    address: "Route nationale N3, Batna",
    latitude: 35.3800,
    longitude: 5.8900,
    images: [
      "https://picsum.photos/seed/prop22a/800/600",
    ],
    amenities: ["Irrigation", "Titre foncier", "Accès route"],
    featured: false,
    available: true,
    yearBuilt: null,
    agentId: 8,
  },

  // More properties for diversity
  {
    title: "Penthouse Alger marine",
    titleAr: "بنتهاوس على مارين الجزائر",
    description: "Extraordinaire penthouse de 200m² avec terrasse de 80m² vue mer 360°. Roof-top privé, cuisine de chef, salle de bain spa. Le nec plus ultra de l'immobilier algérois.",
    type: "sale",
    category: "apartment",
    price: 180000000,
    priceUnit: "DZD",
    area: 200,
    rooms: 5,
    bedrooms: 4,
    bathrooms: 3,
    floor: 12,
    totalFloors: 12,
    wilaya: "Alger",
    commune: "Hussein Dey",
    address: "Marina d'Alger, Hussein Dey",
    latitude: 36.7430,
    longitude: 3.0920,
    images: [
      "https://picsum.photos/seed/prop23a/800/600",
      "https://picsum.photos/seed/prop23b/800/600",
      "https://picsum.photos/seed/prop23c/800/600",
      "https://picsum.photos/seed/prop23d/800/600",
    ],
    amenities: ["Vue mer 360°", "Terrasse", "Parking", "Piscine roof-top", "Conciergerie", "Domotique", "Cuisine chef"],
    featured: true,
    available: true,
    yearBuilt: 2023,
    agentId: 1,
  },
  {
    title: "Villa bord de mer Tipaza",
    titleAr: "فيلا على ساحل البحر تيبازة",
    description: "Magnifique villa de 250m² à 50m de la plage de Tipaza. Accès privatif à la mer, piscine à débordement, 5 chambres. Vue sur les ruines romaines.",
    type: "sale",
    category: "villa",
    price: 95000000,
    priceUnit: "DZD",
    area: 250,
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    floor: 0,
    totalFloors: 2,
    wilaya: "Tipaza",
    commune: "Tipaza Centre",
    address: "Route balnéaire, Tipaza",
    latitude: 36.5940,
    longitude: 2.4490,
    images: [
      "https://picsum.photos/seed/prop24a/800/600",
      "https://picsum.photos/seed/prop24b/800/600",
      "https://picsum.photos/seed/prop24c/800/600",
    ],
    amenities: ["Accès mer", "Piscine", "Jardin", "Vue ruines", "Terrasse", "Barbecue"],
    featured: true,
    available: true,
    yearBuilt: 2019,
    agentId: 1,
  },
  {
    title: "Studio à Oran Carrefour",
    titleAr: "استوديو في كارفور وهران",
    description: "Studio de 35m² bien situé, idéal pour investissement locatif ou première acquisition. Ascenseur, sécurisé, accès aux commerces.",
    type: "sale",
    category: "studio",
    price: 8500000,
    priceUnit: "DZD",
    area: 35,
    rooms: 1,
    bedrooms: 0,
    bathrooms: 1,
    floor: 4,
    totalFloors: 8,
    wilaya: "Oran",
    commune: "Hai El Yasmine",
    address: "Cité Yasmine, Oran",
    latitude: 35.6812,
    longitude: -0.6354,
    images: [
      "https://picsum.photos/seed/prop25a/800/600",
    ],
    amenities: ["Ascenseur", "Interphone", "Parking"],
    featured: false,
    available: true,
    yearBuilt: 2016,
    agentId: 2,
  },
  {
    title: "Entrepôt industriel Alger",
    titleAr: "مستودع صناعي الجزائر",
    description: "Grand entrepôt de 800m² dans la zone industrielle de Rouiba. Hangar hauteur 8m, bureau intégré 50m², accès poids lourds, 3 quais de chargement.",
    type: "commercial",
    category: "commercial",
    price: 350000,
    priceUnit: "DZD",
    area: 800,
    rooms: 2,
    bedrooms: 0,
    bathrooms: 2,
    floor: 0,
    totalFloors: 1,
    wilaya: "Alger",
    commune: "Rouiba",
    address: "Zone Industrielle de Rouiba, Alger",
    latitude: 36.7300,
    longitude: 3.2800,
    images: [
      "https://picsum.photos/seed/prop26a/800/600",
      "https://picsum.photos/seed/prop26b/800/600",
    ],
    amenities: ["Quais chargement", "Electricité triphasée", "Sécurité", "Accès poids lourds", "Bureau"],
    featured: false,
    available: true,
    yearBuilt: 2010,
    agentId: 1,
  },
  {
    title: "Appartement F2 Alger Centre",
    titleAr: "شقة F2 وسط الجزائر",
    description: "Charmant appartement F2 de 65m² en plein cœur d'Alger. Immeuble haussmannien rénové, parquet, moulures. Vue sur la place de la Grande Poste.",
    type: "rent",
    category: "apartment",
    price: 55000,
    priceUnit: "DZD",
    area: 65,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    floor: 3,
    totalFloors: 5,
    wilaya: "Alger",
    commune: "Alger Centre",
    address: "Rue Didouche Mourad, Alger",
    latitude: 36.7378,
    longitude: 3.0612,
    images: [
      "https://picsum.photos/seed/prop27a/800/600",
      "https://picsum.photos/seed/prop27b/800/600",
    ],
    amenities: ["Parquet", "Architecture historique", "Proximité transports"],
    featured: false,
    available: true,
    yearBuilt: 1920,
    agentId: 1,
  },
  {
    title: "Villa de standing à Cheraga",
    titleAr: "فيلا راقية في الشراقة",
    description: "Somptueuse villa de 400m² à Cheraga. Résidence fermée et sécurisée, gardien 24h/24, grande piscine, 6 chambres suite, salon d'apparat 80m², bibliothèque.",
    type: "sale",
    category: "villa",
    price: 160000000,
    priceUnit: "DZD",
    area: 400,
    rooms: 10,
    bedrooms: 6,
    bathrooms: 5,
    floor: 0,
    totalFloors: 3,
    wilaya: "Alger",
    commune: "Chéraga",
    address: "Résidence Royal, Cheraga, Alger",
    latitude: 36.7670,
    longitude: 2.9620,
    images: [
      "https://picsum.photos/seed/prop28a/800/600",
      "https://picsum.photos/seed/prop28b/800/600",
      "https://picsum.photos/seed/prop28c/800/600",
    ],
    amenities: ["Piscine", "Gardien 24h", "Jacuzzi", "Salle sport", "Cinéma maison", "Climatisation centrale", "Jardin"],
    featured: true,
    available: true,
    yearBuilt: 2022,
    agentId: 1,
  },
  {
    title: "F3 à louer Bouzareah",
    titleAr: "F3 للإيجار في بوزريعة",
    description: "Agréable appartement F3 de 80m² à Bouzareah, quartier paisible avec vue sur la baie d'Alger. Bien entretenu, lumineux, parking inclus.",
    type: "rent",
    category: "apartment",
    price: 60000,
    priceUnit: "DZD",
    area: 80,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    floor: 4,
    totalFloors: 7,
    wilaya: "Alger",
    commune: "Bouzaréah",
    address: "Cité Palmiers, Bouzaréah, Alger",
    latitude: 36.7854,
    longitude: 3.0115,
    images: [
      "https://picsum.photos/seed/prop29a/800/600",
      "https://picsum.photos/seed/prop29b/800/600",
    ],
    amenities: ["Vue baie", "Parking", "Ascenseur", "Balcon"],
    featured: false,
    available: true,
    yearBuilt: 2011,
    agentId: 1,
  },
  {
    title: "Duplex à Kouba Alger",
    titleAr: "دوبلكس في القبة - الجزائر",
    description: "Beau duplex de 150m² à Kouba avec terrasse privative de 30m². 4 chambres sur 2 niveaux, cuisine américaine, finitions soignées. Idéal famille.",
    type: "sale",
    category: "apartment",
    price: 42000000,
    priceUnit: "DZD",
    area: 150,
    rooms: 5,
    bedrooms: 4,
    bathrooms: 2,
    floor: 7,
    totalFloors: 8,
    wilaya: "Alger",
    commune: "Kouba",
    address: "Résidence Kouba Heights, Alger",
    latitude: 36.7196,
    longitude: 3.0914,
    images: [
      "https://picsum.photos/seed/prop30a/800/600",
      "https://picsum.photos/seed/prop30b/800/600",
      "https://picsum.photos/seed/prop30c/800/600",
    ],
    amenities: ["Terrasse", "Duplex", "Cuisine américaine", "Parking", "Ascenseur"],
    featured: false,
    available: true,
    yearBuilt: 2020,
    agentId: 1,
  },
];

async function seed() {
  console.log("Seeding agents...");
  // Clear existing data
  await db.delete(propertiesTable);
  await db.delete(agentsTable);

  const insertedAgents = await db.insert(agentsTable).values(agents).returning();
  console.log(`Inserted ${insertedAgents.length} agents`);

  console.log("Seeding properties...");
  const insertedProperties = await db.insert(propertiesTable).values(propertiesSeed).returning();
  console.log(`Inserted ${insertedProperties.length} properties`);
  
  console.log("Seeding complete!");
}

seed().catch(console.error).finally(() => process.exit(0));
